### ISSUE TITLE
Move gems not needed for `test` rake task to new group.

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/modulesync_config#195]
For example...
At the moment, it's not possible to test against puppet versions < 3.7 as puppet-strings depends on this version.

Recently, puppet-blacksmith had rest-client pinned to 1.8 as 2.0 didn't support ruby 1.9.  If puppet-blacksmith had been in a group other than `test` this wouldn't have been so much of an issue.

**Comment by juniorsysadmin** [comment]
+1
Adding a publishing gem group reduces gem dependencies for the testing set and reduces the chances that something breaks when just trying to run unit tests. And this helps to get Pull Requests merged quicker, especially when there is nothing wrong with the submitter's code.

**Comment by bastelfreak** [comment]
we discussed this multiple times on IRC. Currently our release fails because of the github changelog generator and a changed dependency: https://travis-ci.org/voxpupuli/puppet-openvpn/jobs/284429243

We should create the release group, which contains at least:

* github_changelog_generator
* voxpupuli-release
* puppet-blacksmith
* puppet-strings?
