### ISSUE TITLE
Implement topscope-variable-check

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#486]
the awesome @mmerfort developed https://github.com/Sixt/puppet-lint-topscope-variable-check, a puppet-lint plugin to detect/fix variables referencing the top scope with `$::`. We should implement this as soon as the gem is in a working state.

**Comment by ghoneycutt** [comment]
@bastelfreak Do you know at which puppet version this became safe to do? The history of the leading `::` was because of scoping issues in the language and ensuring you are giving a fully qualified name space for a variable and not a relative name space.

I'm in favor of this though would like to know when it became safe so it does not get applied to inappropriate code bases.

**Comment by bastelfreak** [comment]
I think with 4.0? I'm not 100% sure, I would like to forward the question to @binford2k .

**Comment by dhoppe** [comment]
I think this issue can be closed since it has been solved via #582.
